name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
      - name: Install black
        run: pip install black==22.3.0
      - name: Run black
        run: black --check --verbose ./src/